openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      properties:
        image_name:
          title: 构建器镜像名
          type: string
          description: Name for the esxi_builder image
          default: esxi_builder_by_terraform
          x-walrus-ui:
            group: Basic
            order: 2
        image_url:
          title: 镜像 Url
          type: string
          description: URL to download the image from
          default: http://minio.zstack.io:9000/packer/redis-by-packer-image-compressed.qcow2
          x-walrus-ui:
            group: Basic
            order: 3
        backup_storage_name:
          title: 镜像服务器
          type: string
          description: Name of the backup storage to use
          default: bs
          x-walrus-ui:
            group: Basic
            order: 4
        instance_name:
          title: 构建器云主机名称
          type: string
          description: Name for the esxi_builder instance
          default: esxi_builder
          x-walrus-ui:
            group: Basic
            order: 5
        l3_network_name:
          title: 三层网络名称
          type: string
          description: 使用公有或编排网络，确保可以ssh访问
          default: test
          x-walrus-ui:
            group: Basic
            order: 6
        instance_offering_name:
          title: 计算规格名称
          type: string
          description: Name of the instance offering to use
          default: min
          x-walrus-ui:
            group: Basic
            order: 7
        ssh_user:
          title: Ssh User
          type: string
          description: SSH username for remote access
          default: zstack
          readOnly: true
          x-walrus-ui:
            group: Basic
            order: 8
        ssh_password:
          title: Ssh Password
          type: string
          description: SSH password for remote access
          default: ZStack@123
          readOnly: true
          x-walrus-ui:
            group: Basic
            order: 9
        never_stop:
          title: Never Stop
          type: boolean
          description: Whether the instance should never be stopped automatically
          default: true
          x-walrus-ui:
            group: Basic
            order: 10
        esxi_root_password:
          title: Esxi Root Password
          type: string
          description: Root password for the ESXi installation
          default: ZStack@123
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 11
        esxi_iso_url:
          title: 原Esxi Iso Url
          type: string
          description: URL to download the ESXi ISO from
          default: http://192.168.200.100/mirror/iso/vmware/VMware_iso/VMware-VMvisor-Installer-6.5.0.update01-5969303.x86_64.iso
          x-walrus-ui:
            group: Basic
            order: 12
        esxi_iso_filename:
          title: Esxi Iso Filename
          type: string
          description: ESXi ISO文件名,目前仅支持6.5和6.7版本，请保持和iso url的文件名一致
          default: VMware-VMvisor-Installer-6.5.0.update01-5969303.x86_64.iso
          x-walrus-ui:
            group: Basic
            order: 13
        expunge:
          title: 是否彻底删除
          type: boolean
          default: true
          x-walrus-ui:
            group: Basic
            order: 14
      x-walrus-ui:
        groupOrder:
        - Basic
